### ISSUE TITLE
The properties from the Vuex get the unused-property error in the mixin

### ISSUE THREAD

**Issue by Ceall8650** [CyanSalt/eslint-plugin-galaxy#1]
As the screenshot shows, 

When I use the properties from Vuex (`mapState`, `mapActions`,...), 

even the property is used in the methods, I still get the error of `Property "xxx" is never used.`

How could I avoid this situation?
 
![image](https://github.com/CyanSalt/eslint-plugin-galaxy/assets/4955198/e0697bf6-2063-4f2b-9d93-4997f487aea9)

**Comment by CyanSalt** [comment]
This looks like a special false positive because the object is not recognized as a component.

I'll fix this, but you may need to mark the object with `// @vue/component` in your JS or TS file. See [Docs](https://eslint.vuejs.org/user-guide/#how-does-eslint-detect-components)

**Comment by CyanSalt** [comment]
Fixed in [v1.32.1](https://github.com/CyanSalt/eslint-plugin-galaxy/releases/tag/v1.32.1)
